# Generated by Django 5.2 on 2025-04-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('operating_system', models.CharField(choices=[('Windows Server', 'Windows Server'), ('Ubuntu', 'Ubuntu'), ('CentOS', 'CentOS'), ('Debian', 'Debian'), ('Otros', 'Otros')], max_length=50)),
                ('ram', models.IntegerField(help_text='Memoria RAM en GB')),
                ('storage', models.FloatField(help_text='Capacidad del disco en GB')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Mantenimiento', 'Mantenimiento')], default='Activo', max_length=20)),
            ],
        ),
    ]
