# Generated by Django 5.2 on 2025-04-02 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_server_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='user',
        ),
    ]
